<?php
/**
 * Jollof Living — host-dashboard
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
require_once JL_INC . '/view.php';

Auth::requireLogin();

View::header('host-dashboard');
View::footer();
