/* Generates the thin PHP page controllers in public_html/.
   Each page loads the bootstrap, renders the shared chrome and lets the
   bundle paint its view from the window.JL payload. Pages that need
   per-request data (a stay, a booking, a blog post) add their own lookup. */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public_html');
fs.mkdirSync(OUT, { recursive: true });

const simple = [
  ['index', ''],
  ['stays', ''],
  ['map', ''],
  ['collections', ''],
  ['experiences', ''],
  ['reviews', ''],
  ['blog', ''],
  ['help', ''],
  ['membership', ''],
  ['giftcards', ''],
  ['referral', ''],
  ['business', ''],
  ['about', ''],
  ['app', ''],
  ['future', ''],
  ['concierge', ''],
  ['neighborhoods', ''],
  ['404', ''],
];

const authed = ['messages', 'notifications', 'trips', 'wishlist', 'compare', 'account', 'payments'];
// host-onboarding is reachable by any signed-in customer (it is how you
// become an owner); the dashboard itself is owner-only.
const hostPages = ['host-onboarding'];
const ownerPages = ['host-dashboard'];

const head = `<?php
/**
 * Jollof Living — {PAGE}
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';
`;

function write(name, body) {
  fs.writeFileSync(path.join(OUT, name + '.php'), body.replace(/\{PAGE\}/g, name));
}

/* ---------------------------------------------------------- simple pages */
for (const [name] of simple) {
  write(name, head + `
View::header('${name}');
View::footer();
`);
}

/* --------------------------------------------------------- guest pages */
for (const name of authed) {
  write(name, head + `
Auth::requireLogin();

View::header('${name}');
View::footer();
`);
}

/* ----------------------------------------------------------- host pages */
for (const name of hostPages) {
  write(name, head + `
Auth::requireLogin();

View::header('${name}');
View::footer();
`);
}

/* ---------------------------------------------------------- owner pages */
for (const name of ownerPages) {
  write(name, head + `
Auth::requireHost();

View::header('${name}');
View::footer();
`);
}

/* --------------------------------------------------------------- auth */
write('auth', head + `
// already signed in? go where they were heading
if (Auth::check()) {
    redirect($_GET['next'] ?? 'account.php');
}
$mode = ($_GET['mode'] ?? 'signin') === 'register' ? 'register' : 'signin';

View::header('auth', [
    'title' => $mode === 'register' ? 'Create your account | Jollof Living' : 'Sign in | Jollof Living',
]);
View::footer();
`);

write('logout', `<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';

if (Auth::check()) {
    audit((string) (Auth::user()['email'] ?? 'user'), 'Signed out', 'info');
}
Auth::logout();
redirect('');
`);

/* -------------------------------------------------------------- admin */
write('admin-login', head + `
if (Auth::isAdmin()) {
    redirect($_GET['next'] ?? 'admin.php');
}

View::header('admin-login');
View::footer();
`);

write('admin', head + `
Auth::requireAdmin();

$extra = [
    'charts' => [
        'revenue' => Repo::revenueSeries(12),
        'byCity'  => Repo::revenueByCity(),
    ],
    'cmsBlocks' => array_map(static fn($b) => [
        'id'     => (int) $b['id'],
        'title'  => $b['title'],
        'body'   => (string) $b['body'],
        'status' => $b['status'],
    ], DB::all('SELECT * FROM cms_blocks ORDER BY id')),
    'campaigns' => array_map(static fn($c) => [
        'id'           => (int) $c['id'],
        'code'         => $c['code'],
        'name'         => $c['name'],
        'window_label' => $c['window_label'],
        'status'       => $c['status'],
    ], DB::all('SELECT * FROM campaigns ORDER BY id')),
    'roles' => array_map(static fn($r) => [
        $r['role'],
        [
            'admin'     => 'Full platform access',
            'host'      => 'Own listings, calendar and payouts',
            'corporate' => 'Business travel portal and invoicing',
            'guest'     => 'Book, review and message',
        ][$r['role']] ?? 'Platform access',
        (int) $r['n'],
    ], DB::all('SELECT role, COUNT(*) AS n FROM users GROUP BY role ORDER BY n DESC')),
];

View::header('admin', ['extra' => $extra]);
View::footer();
`);

/* ------------------------------------------------- dynamic: single stay */
write('stay', head + `
$slug = (string) ($_GET['p'] ?? '');
$property = $slug !== '' ? Repo::property($slug) : null;

if (!$property || $property['status'] !== 'live') {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

Repo::recordView((int) $property['pid']);

$extra = [
    'stay'    => $property,
    'blocked' => BookingService::blockedRanges((int) $property['pid']),
];

View::header('stay-' . $property['id'], [
    'metaKey' => 'stays',
    'title'   => $property['name'] . ' — Luxury Stay | Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $property['desc']), 0, 300),
    'image'   => base_path() . '/assets/img/' . (View::images()[$property['img']] ?? 'hero.jpg'),
    'extra'   => $extra,
]);
View::noscript(
    '<h1>' . e($property['name']) . '</h1>'
    . '<p>' . e((string) $property['area']) . ', ' . e((string) $property['city']) . ' · '
    . e(money((int) $property['price'])) . ' per night · ' . e((string) $property['rating']) . '★ ('
    . (int) $property['reviews'] . ' reviews)</p>'
    . '<p>' . e((string) $property['desc']) . '</p>'
    . '<p><a href="' . e(url('booking.php?p=' . urlencode($property['id']))) . '">Reserve this residence</a></p>'
);
View::footer();
`);

/* ---------------------------------------------- dynamic: booking wizard */
write('booking', head + `
$slug = (string) ($_GET['p'] ?? '');
$property = $slug !== '' ? Repo::property($slug) : null;

if (!$property || $property['status'] !== 'live') {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

$extra = [
    'stay'    => $property,
    'blocked' => BookingService::blockedRanges((int) $property['pid']),
];

View::header('booking-' . $property['id'], [
    'metaKey' => 'stays',
    'title'   => 'Complete your reservation — ' . $property['name'] . ' | Jollof Living',
    'desc'    => 'Secure checkout for ' . $property['name'] . ' — split payments, promo codes and escrow protection.',
    'extra'   => $extra,
]);
View::footer();
`);

/* ------------------------------------------------------ dynamic: confirm */
write('confirm', head + `
$ref = (string) ($_GET['ref'] ?? '');
$booking = $ref !== '' ? BookingService::find($ref) : null;

// only the guest who made it (or an admin) may view a reservation
if ($booking && $booking['user_id'] && (int) $booking['user_id'] !== (int) (Auth::id() ?? 0) && !Auth::isAdmin()) {
    $booking = null;
}

if (!$booking) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

$extra = ['booking' => [
    'ref'          => $booking['ref'],
    'prop'         => $booking['property_slug'],
    'name'         => $booking['property_name'],
    'img'          => $booking['img'],
    'area'         => $booking['area'],
    'city'         => $booking['city'],
    'in'           => $booking['checkin'],
    'out'          => $booking['checkout'],
    'nights'       => (int) $booking['nights'],
    'guests'       => (int) $booking['guests'],
    'method'       => $booking['pay_method'],
    'addons'       => $booking['addons'],
    'split'        => (int) $booking['split_payment'] === 1,
    'req'          => (int) $booking['is_request'] === 1,
    'total'        => (int) $booking['total'],
    'status'       => $booking['status'],
    'code'         => $booking['checkin_code'],
    'pointsEarned' => (int) $booking['points_earned'],
]];

View::header('confirm', ['extra' => $extra]);
View::footer();
`);

/* ------------------------------------------------- dynamic: neighbourhood */
write('neighborhood', head + `
$slug = (string) ($_GET['n'] ?? '');
$hood = $slug !== '' ? Repo::neighborhood($slug) : null;

if (!$hood) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

View::header('neighborhood-' . $hood['id'], [
    'metaKey' => 'neighborhoods',
    'title'   => $hood['name'] . ' — Neighbourhood Guide | Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $hood['desc']), 0, 300),
    'extra'   => ['hood' => $hood],
]);
View::noscript('<h1>' . e($hood['name']) . '</h1><p>' . e((string) $hood['desc']) . '</p>');
View::footer();
`);

/* --------------------------------------------------- dynamic: blog post */
write('blog-post', head + `
$slug = (string) ($_GET['s'] ?? '');
$post = $slug !== '' ? Repo::blogPost($slug) : null;

if (!$post) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

View::header('blog-' . $post['slug'], [
    'metaKey' => 'blog',
    'title'   => $post['title'] . ' | The Journal — Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $post['excerpt']), 0, 300),
    'image'   => base_path() . '/assets/img/' . (View::images()[$post['img']] ?? 'hero.jpg'),
    'extra'   => ['post' => $post],
]);
View::noscript(
    '<h1>' . e($post['title']) . '</h1>'
    . implode('', array_map(static fn($p) => '<p>' . e($p) . '</p>', $post['body']))
);
View::footer();
`);

/* ----------------------------------------------------------- host page */
write('host', head + `
View::header('host');
View::footer();
`);

console.log('generated', fs.readdirSync(OUT).filter((f) => f.endsWith('.php')).length, 'php pages');
