/* ============================================================
   Jollof Living — seed generator
   Reads the original content constants (tools/seed-source/data.legacy.js) and emits
   database/seed.sql : a plain MySQL dump that can be imported
   through cPanel → phpMyAdmin, or by install/install.php.

   Run:  node tools/gen_seed.mjs
   ============================================================ */
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const raw = fs.readFileSync(path.join(ROOT, 'tools/seed-source/data.legacy.js'), 'utf8');
const names = [...raw.matchAll(/^const ([A-Z_]+) =/gm)].map((m) => m[1]);
const tmp = path.join(os.tmpdir(), 'jl-data-' + Date.now() + '.mjs');
fs.writeFileSync(tmp, raw.replace(/^"use strict";/m, '') + `\nexport const ALL={${names.join(',')}};`);
const { ALL } = await import('file://' + tmp);
fs.unlinkSync(tmp);

const D = ALL;
const out = [];
const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  // Double the quote rather than backslash-escaping: that is ANSI SQL, so the
  // same seed file loads on MySQL (HostGator) and on SQLite (local dev).
  return "'" + String(v).replace(/'/g, "''").replace(/\r/g, '') + "'";
};
const insert = (table, cols, rows) => {
  if (!rows.length) return;
  out.push(`INSERT INTO ${table} (${cols.join(', ')}) VALUES`);
  out.push(rows.map((r) => '  (' + r.map(q).join(', ') + ')').join(',\n') + ';');
  out.push('');
};

out.push('-- ============================================================');
out.push('-- Jollof Living — seed data (generated by tools/gen_seed.mjs)');
out.push('-- ============================================================');
out.push('SET NAMES utf8mb4;');
out.push('');

/* ------------------------------------------------------------- users */
const adminHash = '$2y$10$e0NRl6nZ2cXjTuJ9Ii9K1uV1oSJ2xg2Yy3s3zXqf7z0eG7HpB2mFa'; // placeholder, reset by installer
insert(
  'users',
  ['id', 'name', 'email', 'phone', 'password_hash', 'role', 'is_host', 'tier', 'points', 'city', 'status', 'status_level', 'kyc_verified', 'referral_code'],
  [
    [1, 'Adebayo Ogunlesi', 'adebayo@jollofliving.com', '+234 801 000 0001', adminHash, 'guest', 1, 'gold', 62400, 'Lagos', 'Verified', 'ok', 1, 'ADEBAYO10'],
    [2, 'Jollof Operations', 'ops@jollofliving.com', '+234 801 000 0000', adminHash, 'admin', 0, 'platinum', 0, 'Lagos', 'Verified', 'ok', 1, null],
    ...D.ADMIN_STATE.users.slice(1).map((u, i) => [
      i + 3,
      u[0],
      /@/.test(u[1]) && !u[1].endsWith('...')
        ? u[1]
        : u[0].toLowerCase().replace(/[^a-z]+/g, '.') + '@example.com',
      null,
      null,
      /Host/.test(u[2]) ? 'host' : /Corporate/.test(u[2]) ? 'corporate' : 'guest',
      /Host/.test(u[2]) ? 1 : 0,
      (u[3] || 'bronze').toLowerCase() === '—' ? 'bronze' : (u[3] || 'bronze').toLowerCase(),
      0,
      null,
      u[5],
      u[6] === 'ok' ? 'ok' : u[6] === 'bad' ? 'bad' : 'warn',
      u[5] === 'Verified' ? 1 : 0,
      null,
    ]),
  ]
);

/* -------------------------------------------------------- properties */
const propId = {};
D.PROPERTIES.forEach((p, i) => (propId[p.id] = i + 1));
insert(
  'properties',
  ['id', 'slug', 'name', 'area', 'city', 'img', 'price', 'old_price', 'rating', 'reviews_count', 'beds', 'baths', 'guests', 'ptype', 'badge', 'badge_gold', 'instant', 'policy', 'map_x', 'map_y', 'featured', 'is_new', 'tour', 'floor_label', 'sold_out', 'description', 'ai_summary', 'host_id', 'status', 'sort_order'],
  D.PROPERTIES.map((p, i) => [
    propId[p.id], p.id, p.name, p.area, p.city, p.img, p.price, p.oldPrice ?? null,
    p.rating, p.reviews, p.beds, p.baths, p.guests, p.type, p.badge ?? null,
    p.badgeGold ? 1 : 0, p.instant ? 1 : 0, p.policy, p.map[0], p.map[1],
    p.featured ? 1 : 0, p.new ? 1 : 0, p.tour ? 1 : 0, p.floor ?? null,
    p.soldOut ?? null, p.desc, p.aiSummary ?? null, 1, 'live', i,
  ])
);

insert('property_amenities', ['property_id', 'amenity', 'sort_order'],
  D.PROPERTIES.flatMap((p) => (p.amens || []).map((a, i) => [propId[p.id], a, i])));

insert('property_scores', ['property_id', 'cleanliness', 'accuracy', 'communication', 'location', 'checkin', 'value_score'],
  D.PROPERTIES.filter((p) => p.scores).map((p) => [propId[p.id], p.scores.c, p.scores.a, p.scores.com, p.scores.loc, p.scores.ci, p.scores.v]));

insert('property_nearby', ['property_id', 'place', 'distance', 'sort_order'],
  D.PROPERTIES.flatMap((p) => (p.nearby || []).map((n, i) => [propId[p.id], n[0], n[1], i])));

insert('reviews', ['property_id', 'author', 'meta', 'body', 'rating', 'status'],
  D.PROPERTIES.flatMap((p) => (p.reviewsList || []).map((r) => [propId[p.id], r[0], r[1], r[2], 5.0, 'published'])));

/* -------------------------------------------------------- collections */
const colId = {};
D.COLLECTIONS.forEach((c, i) => (colId[c.id] = i + 1));
insert('collections', ['id', 'slug', 'name', 'sub', 'img', 'wide', 'tall', 'sort_order'],
  D.COLLECTIONS.map((c, i) => [colId[c.id], c.id, c.name, c.sub, c.img, c.wide ? 1 : 0, c.tall ? 1 : 0, i]));

insert('collection_properties', ['collection_id', 'property_id', 'sort_order'],
  Object.entries(D.COLLECTION_MAP).flatMap(([cid, ids]) =>
    ids.filter((id) => propId[id]).map((id, i) => [colId[cid], propId[id], i])));

/* ----------------------------------------------------- neighbourhoods */
const nbId = {};
D.NEIGHBORHOODS.forEach((n, i) => (nbId[n.id] = i + 1));
insert('neighborhoods', ['id', 'slug', 'name', 'tag', 'img', 'avg_price', 'stays_count', 'description', 'sort_order'],
  D.NEIGHBORHOODS.map((n, i) => [nbId[n.id], n.id, n.name, n.tag, n.img, n.avg, n.stays, n.desc, i]));

insert('neighborhood_items', ['neighborhood_id', 'kind', 'item', 'sort_order'],
  D.NEIGHBORHOODS.flatMap((n) =>
    ['dining', 'night', 'transport', 'safety', 'culture'].flatMap((k) =>
      (n[k] || []).map((v, i) => [nbId[n.id], k, v, i]))));

/* -------------------------------------------------------- experiences */
insert('experiences', ['id', 'slug', 'name', 'category', 'img', 'price', 'duration', 'description', 'active', 'sort_order'],
  D.EXPERIENCES.map((e, i) => [i + 1, e.id, e.name, e.cat, e.img, e.price, e.dur, e.desc, 1, i]));

/* --------------------------------------------------------------- blog */
insert('blog_posts', ['id', 'slug', 'category', 'title', 'date_label', 'read_time', 'img', 'excerpt', 'body', 'published', 'sort_order'],
  D.BLOG.map((b, i) => [i + 1, b.slug, b.cat, b.title, b.date, b.read, b.img, b.excerpt, JSON.stringify(b.body), 1, i]));

/* ------------------------------------------------------ content bits */
insert('testimonials', ['author', 'meta', 'quote', 'active', 'sort_order'],
  D.TESTIMONIALS.map((t, i) => [t[0], t[1], t[2], 1, i]));

insert('faqs', ['question', 'answer', 'category', 'sort_order'],
  D.FAQS.map((f, i) => [f[0], f[1], null, i]));

insert('help_categories', ['slug', 'name', 'article_count', 'icon', 'sort_order'],
  D.HELP_CATEGORIES.map((h, i) => [h.id, h.name, h.n, h.ico, i]));

insert('roadmap', ['phase', 'title', 'description', 'status', 'sort_order'],
  D.ROADMAP.map((r, i) => [r.ph, r.title, r.desc, r.status, i]));

/* ----------------------------------------------------- pricing config */
insert('fx_rates', ['code', 'symbol', 'rate', 'decimals', 'sort_order'],
  Object.entries(D.FX).map(([code, f], i) => [code, f.s, f.r, f.d, i]));

insert('addons', ['akey', 'name', 'price', 'is_percent', 'icon', 'note', 'active', 'sort_order'],
  Object.entries(D.ADDONS).map(([k, a], i) => [k, a.name, a.price, a.price < 1 ? 1 : 0, a.ico, a.note, 1, i]));

insert('promos', ['code', 'label', 'off', 'flat', 'active'],
  Object.entries(D.PROMOS).map(([k, p]) => [k, p.label, p.off || 0, p.flat || 0, 1]));

insert('pay_methods', ['mkey', 'name', 'note', 'icon', 'active', 'sort_order'],
  D.PAY_METHODS.map((p, i) => [p.id, p.name, p.note, p.ico, 1, i]));

insert('settings', ['skey', 'svalue'],
  Object.entries(D.RATES).map(([k, v]) => ['rate_' + k, String(v)]).concat([
    ['site_name', 'Jollof Living'],
    ['site_tagline', 'Luxury Living, African Soul'],
    ['site_domain', 'www.jollofliving.com'],
    ['default_currency', 'NGN'],
    ['contact_email', 'hello@jollofliving.com'],
    ['contact_phone', '+234 800 000 0000'],
    ['host_take_rate', '0.12'],
  ]));

/* ---------------------------------------------------------- membership */
const mult = (m) => parseInt(String(m).replace(/\D/g, ''), 10) || 5;
insert('tiers', ['tkey', 'letter', 'name', 'requirement', 'points_label', 'min_points', 'multiplier', 'featured', 'sort_order'],
  D.TIERS.map((t, i) => [t.key, t.letter, t.name, t.req, t.pts, parseInt(String(t.req).replace(/[^\d]/g, ''), 10) || 0, mult(t.mult), t.featured ? 1 : 0, i]));

insert('tier_perks', ['tkey', 'perk', 'sort_order'],
  D.TIERS.flatMap((t) => t.perks.map((p, i) => [t.key, p, i])));

insert('points_ledger', ['user_id', 'date_label', 'description', 'amount', 'kind'],
  D.POINTS_LEDGER.map((r) => [1, r[0], r[1], parseInt(r[2].replace(/[^\d-]/g, ''), 10) * (r[3] === 'redeem' ? -1 : 1), r[3]]));

/* --------------------------------------------------------------- comms */
const cvId = {};
D.CONVERSATIONS.forEach((c, i) => (cvId[c.id] = i + 1));
// 'kind' routes replies: concierge threads are answered by the bot, host
// threads are emailed to the host, support threads go to the ops inbox.
const convKind = (id) => (id === 'concierge' ? 'concierge' : id === 'support' ? 'support' : 'host');
insert('conversations', ['id', 'user_id', 'ckey', 'kind', 'name', 'subtitle', 'online', 'preview'],
  D.CONVERSATIONS.map((c, i) => [
    i + 1, 1, c.id, convKind(c.id), c.name, c.sub, c.online ? 1 : 0,
    (c.msgs && c.msgs.length ? String(c.msgs[c.msgs.length - 1].text).replace(/<[^>]*>/g, '').slice(0, 120) : null),
  ]));

insert('messages', ['conversation_id', 'sender', 'body', 'time_label', 'read_flag'],
  D.CONVERSATIONS.flatMap((c) => c.msgs.map((m) => [cvId[c.id], m.from === 'me' ? 'me' : 'bot', m.text, m.t, m.read ? 1 : 0])));

insert('notifications', ['user_id', 'icon', 'title', 'body', 'time_label', 'read_flag'],
  D.NOTIFS.map((n) => [1, n.ico, n.title, n.body, n.time, n.unread ? 0 : 1]));

/* ------------------------------------------------------------ ops data */
insert('campaigns', ['code', 'name', 'window_label', 'status', 'revenue', 'level'],
  D.ADMIN_STATE.campaigns.map((c) => [c[0], c[1], c[2], c[3], c[4] === 'ok' ? c[4] : c[4], c[5] || 'info']));

insert('moderation_queue', ['item', 'ref_slug', 'item_type', 'note', 'level', 'status'],
  D.ADMIN_STATE.moderation.map((m) => [m[0], m[1] === '—' ? null : m[1], m[2], m[3], m[4], 'open']));

insert('fraud_flags', ['code', 'subject', 'reason', 'score', 'level', 'status'],
  D.ADMIN_STATE.fraud.map((f) => [f[0], f[1], f[2], parseInt(f[3], 10), f[4], 'open']));

insert('audit_log', ['actor', 'action', 'level', 'time_label'],
  D.ADMIN_STATE.audit.map((a) => [a[1], a[2], a[3], a[0]]));

insert('cms_blocks', ['block_key', 'title', 'body', 'status', 'owner', 'updated_label'],
  D.ADMIN_STATE.cms.map((c, i) => ['block-' + (i + 1), c[0], null, c[1], c[3], c[2] === '—' ? null : c[2]]));

/* --------------------------------------------------------- page titles */
const PAGE_META = {
  index: ['Jollof Living - Luxury Living, African Soul', 'Premium luxury apartments in Lagos & Abuja - exclusive short-term and long-term stays with concierge, escrow payments and AI.'],
  stays: ['The Collection - Luxury Stays | Jollof Living', 'Browse exclusive residences across Lekki, Victoria Island, Ikoyi, Banana Island and Abuja - filters, map and instant booking.'],
  map: ['Explore the Map | Jollof Living', 'Interactive map of every Jollof Living residence in Lagos & Abuja with live nightly rates.'],
  collections: ['Curated Collections | Jollof Living', 'Waterfront escapes, sky penthouses, Abuja executive, heritage homes, romantic retreats and family villas.'],
  experiences: ['Experiences | Jollof Living', 'Boat cruises, private chefs, spa rituals, art tours, airport transfers, event hosting and VIP shopping.'],
  reviews: ['Reviews | Jollof Living', 'Verified guest reviews, AI summaries and the platform rules that keep them honest.'],
  blog: ['The Journal | Jollof Living', 'Travel guides, culture pieces and stories from the Jollof Living editorial desk.'],
  help: ['Help Centre | Jollof Living', 'Answers, dispute support, emergency assistance and 24/7 live help.'],
  membership: ['Jollof Club - Bronze to Platinum | Jollof Living', 'Earn Jollof Points on every stay, climb tiers, redeem rewards and gift cards.'],
  giftcards: ['Gift Cards | Jollof Living', 'Digital gift cards delivered by email or WhatsApp - never expire.'],
  referral: ['Refer & Earn - Give N10,000, Get N10,000 | Jollof Living', 'The most generous referral in Nigerian travel.'],
  business: ['Jollof for Business | Jollof Living', 'Corporate stays with centralized billing, PO support and travel policy enforcement.'],
  about: ['About Jollof Living - Luxury Living, African Soul', "The story, standards and safeguards behind Nigeria's premium stay platform."],
  app: ['Mobile App | Jollof Living', 'Keyless check-in, live messaging, wallet passes and voice booking.'],
  future: ['Roadmap | Jollof Living', "Live product roadmap - what's shipping, what's building, what's dreaming."],
  concierge: ['Jollof Concierge - AI, 24/7 | Jollof Living', 'Ask about stays, prices, itineraries, transfers and chefs.'],
  messages: ['Messages | Jollof Living', 'Real-time chat with hosts, support and Jollof.'],
  notifications: ['Notifications | Jollof Living', 'Booking alerts, price drops and promotions.'],
  trips: ['My Trips | Jollof Living', 'Every reservation, request and stay in one place.'],
  wishlist: ['Wishlist | Jollof Living', 'Named lists, price-drop alerts and sharing.'],
  compare: ['Compare Residences | Jollof Living', 'Side-by-side pricing, ratings and amenities - up to 3 residences.'],
  account: ['My Account | Jollof Living', 'KYC, verification, profile, security and preferences.'],
  auth: ['Sign In | Jollof Living', 'Email, phone or social - onboarding takes 90 seconds.'],
  host: ['Host with Jollof Living', 'List your residence, keep 88% - photography, pricing intelligence, guest screening and payouts handled.'],
  'host-onboarding': ['Listing Wizard | Jollof Living', 'Guided step-by-step listing creation - save and return anytime.'],
  'host-dashboard': ['Host Dashboard | Jollof Living', 'Earnings, occupancy, calendar, pricing, AI tools, co-hosts and payouts.'],
  payments: ['Payments & Payouts | Jollof Living', 'Invoices for guests, earnings and payouts for hosts - NGN, USD, GBP, EUR.'],
  admin: ['Back Office | Jollof Living', 'Platform operations - GMV, moderation, users, campaigns, fraud AI, CMS and audit.'],
  'admin-login': ['Back Office Sign In | Jollof Living', 'Restricted sign-in for the Jollof Living platform operations console.'],
  '404': ['Page Not Found | Jollof Living', "This address doesn't exist - yet."],
  confirm: ['Booking Confirmed | Jollof Living', 'Your reservation is confirmed - invoice, check-in details and points earned.'],
  neighborhoods: ['Neighbourhood Guides | Jollof Living', 'Insider guides to Lagos and Abuja - dining, nightlife, transport and safety.'],
};
insert('page_meta', ['page_key', 'title', 'description'],
  Object.entries(PAGE_META).map(([k, v]) => [k, v[0], v[1]]));

fs.mkdirSync(path.join(ROOT, 'database'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'database/seed.sql'), out.join('\n'));
console.log('wrote database/seed.sql (' + out.join('\n').length + ' bytes)');
