/* ============================================================
   JOLLOF LIVING — data.js  (all platform data)
   ============================================================ */
"use strict";

const FX = { NGN:{s:"\u20A6",r:1,d:0}, USD:{s:"$",r:1/1550,d:0}, GBP:{s:"\u00A3",r:1/2140,d:0}, EUR:{s:"\u20AC",r:1/1830,d:0} };

const RATES = { cleaning:15000, service:0.08, vat:0.075, weeklyDisc:0.12, monthlyDisc:0.25, deposit:0.20, insurance:0.03 };
const PROMOS = { JOLLOF10:{off:0.10,label:"10% off your stay"}, WELCOME5:{off:0.05,label:"5% off first booking"}, REFER5000:{off:0, flat:5000, label:"\u20A65,000 off" } };
const ADDONS = {
  transfer:{name:"Airport transfer", price:25000, ico:"car", note:"Vetted luxury SUV · both ways"},
  welcome:{name:"Curated welcome basket", price:15000, ico:"gift", note:"Nigerian snacks, wine & a handwritten note"},
  housekeeping:{name:"Mid-stay housekeeping", price:20000, ico:"broom", note:"Once per 7 nights"},
  lateco:{name:"Late check-out · 2pm", price:10000, ico:"clock", note:"Subject to availability"},
  insurance:{name:"Stay protection (3%)", price:0.03, ico:"shield", note:"Covers cancellations & damage"},
  carbon:{name:"Carbon offset", price:2500, ico:"leaf", note:"Verified offset program"},
  exp:{name:"Signature experience bundle", price:60000, ico:"spark", note:"Boat cruise + private chef for two"},
};

const PROPERTIES = [
  {
    id:"onyx", name:"The Onyx Penthouse", area:"Lekki Phase 1", city:"Lagos", img:"p1",
    price:185000, oldPrice:210000, rating:4.97, reviews:128, beds:3, baths:3.5, guests:6,
    type:"Penthouse", badge:"Jollof Verified", badgeGold:true, instant:true, policy:"moderate",
    acreage:"Lekki", map:[0.29,0.72], featured:true, new:false, tour:true, floor:"3 Bed Penthouse",
    desc:"A dark, cinematic penthouse in the sky above Lekki Phase 1. Black marble walls, brass detailing and a private cinema — engineered for quiet drama, with the Lagos skyline flickering beyond 12-foot glass.",
    amens:["Infinity pool","Private cinema","Smart home","Gym","Rooftop terrace","Chef's kitchen","Fast Wi-Fi (1Gbps)","24/7 security","Backup generator","Concierge on call"],
    scores:{c:4.9,a:5.0,com:5.0,loc:4.9,ci:5.0,v:4.8},
    aiSummary:"Guests love the cinema room, the flawless Wi-Fi for video calls, and the concierge's speed. A few noted the lift can be slow at peak hours.",
    reviewsList:[["Adaeze O.","Lagos · Apr 2026","The cinema room alone is worth it. Spotless, concierge arranged a private chef — impeccable."],["James K.","London · Jun 2026","Feels like a five-star hotel floor, but entirely yours. Escrow payment gave total peace of mind."],["Chuka E.","Abuja · Aug 2026","Smart-home everything, blackout blinds, flawless Wi-Fi for calls. Best stay I've had in Lagos."]],
    nearby:[["Ocean Basket Restaurant","1.2 km"],["Landmark Beach","3.4 km"],["Lekki Conservation Centre","6.1 km"],["Palms Mall","2.0 km"],["Nike Art Gallery","4.6 km"]],
  },
  {
    id:"ocean-spearl", name:"Ocean Pearl Suite", area:"Victoria Island", city:"Lagos", img:"p2",
    price:145000, oldPrice:null, rating:4.92, reviews:96, beds:2, baths:2, guests:4,
    type:"Oceanfront Suite", badge:"Superhost", badgeGold:false, instant:true, policy:"flexible",
    acreage:"Victoria Island", map:[0.52,0.42], featured:true, new:false, tour:true, floor:"2 Bed Suite",
    desc:"Wake to the Atlantic. A serene two-bedroom suite with a private balcony over the water, soft linen, warm oak and a slow morning light that turns the ocean to silver.",
    amens:["Ocean view balcony","King beds","Daily housekeeping","Smart TV + Netflix","Fast Wi-Fi","Backup power","Airport pickup available","Espresso bar"],
    scores:{c:4.9,a:4.9,com:4.9,loc:5.0,ci:4.9,v:4.8},
    aiSummary:"Guests consistently praise the sunrise view and digital check-in. The building's gym gets a few mentions as small.",
    reviewsList:[["Funmi A.","Lagos · Mar 2026","The balcony view at sunrise is unbeatable. Concierge had a boat booked in ten minutes."],["Daniel M.","Accra · Jun 2026","Spotless, quiet, and the digital check-in meant midnight arrival was effortless."],["Sarah B.","New York · Aug 2026","Long-stay discount + split payment made a month here very comfortable."]],
    nearby:[["Eko Hotel & Suites","1.5 km"],["Landmark Event Centre","2.8 km"],["Bar Beach","1.1 km"],["Cubana Lagos","2.2 km"]],
  },
  {
    id:"villa-azur", name:"Villa Azur", area:"Banana Island", city:"Lagos", img:"p3",
    price:420000, oldPrice:null, rating:4.99, reviews:74, beds:4, baths:5, guests:8,
    type:"Private Villa", badge:"Jollof Verified", badgeGold:true, instant:false, policy:"strict",
    acreage:"Banana Island", map:[0.36,0.56], featured:true, new:false, tour:true, floor:"4 Bed Villa",
    soldOut:"2026-12-20/2027-01-05",
    desc:"Banana Island's quietest address. A private infinity pool melting into the lagoon, palm-framed terraces, and a villa team on call. This is Nigerian luxury at its most unhurried.",
    amens:["Private infinity pool","Lagoon frontage","Full villa team","Wine cellar","Poolside bar","Private gym","Event hosting","Boat jetty","Smart home","Secure parking"],
    scores:{c:5.0,a:5.0,com:5.0,loc:5.0,ci:5.0,v:5.0},
    aiSummary:"Perfect scores across the board. Guests highlight the boat jetty and the invisible-but-present villa team. High demand — book early or join the waitlist.",
    reviewsList:[["Bolanle T.","Lagos · Feb 2026","We hosted a small engagement here. The team was invisible until we needed them — flawless."],["Hans W.","Berlin · May 2026","The best villa we've stayed at anywhere in Africa. The boat jetty is a touch of genius."],["Zainab M.","Dubai · Jul 2026","Escrow release only after check-in confirmation — exactly how luxury platforms should work."]],
    nearby:[["Banana Island Shopping Court","1.0 km"],["Ikoyi Golf Club","4.2 km"],["The Wheatbaker","5.0 km"],["Nike Art Gallery","6.5 km"]],
  },
  {
    id:"sky-garden", name:"The Sky Garden Terrace", area:"Ikoyi", city:"Lagos", img:"p4",
    price:210000, oldPrice:null, rating:4.95, reviews:143, beds:3, baths:3, guests:6,
    type:"Terrace Residence", badge:"Superhost", badgeGold:false, instant:true, policy:"moderate",
    acreage:"Ikoyi", map:[0.47,0.68], featured:true, new:false, tour:true, floor:"3 Bed Terrace",
    desc:"A lantern-lit rooftop over Ikoyi. Outdoor lounge, heat lamps, and the whole lagoon as your backdrop — designed for golden-hour dinners and long, warm nights.",
    amens:["Rooftop terrace","Outdoor lounge","Lagoon view","BBQ + pizza oven","Wine fridge","Backup generator","Smart locks","Sonos sound"],
    scores:{c:4.9,a:4.9,com:5.0,loc:4.9,ci:5.0,v:4.9},
    aiSummary:"The terrace is the star — guests mention sunsets constantly. Nightlife watchers note street noise on weekends; earplugs provided.",
    reviewsList:[["Tobi F.","Lagos · Jan 2026","Sunsets from this terrace should be illegal. One of Lagos' best-kept secrets."],["Anna P.","Paris · Apr 2026","Beautiful, airy, and the welcome package with chin-chin and wine was so thoughtful."],["Emeka N.","Enugu · Aug 2026","Booked via the AI concierge — three messages and it was done."]],
    nearby:[["Awolowo Road boutique strip","1.4 km"],["The George Hotel","0.9 km"],["Ikoyi Golf Club","2.3 km"],["Rooftop M Restaurant","1.1 km"]],
  },
  {
    id:"maitama", name:"Maitama Executive Residence", area:"Maitama", city:"Abuja", img:"p5",
    price:165000, oldPrice:null, rating:4.90, reviews:88, beds:2, baths:2.5, guests:4,
    type:"Executive Suite", badge:"Corporate Ready", badgeGold:false, instant:true, policy:"flexible",
    acreage:"Maitama", map:[0.75,0.2], featured:false, new:false, tour:true, floor:"2 Bed Executive",
    desc:"The address of choice for dignitaries and executives. A calm, brass-lit residence above the green hills of Maitama, minutes from the Central Business District.",
    amens:["Hill view","Boss-friendly desk","Meeting corner","Fast fibre Wi-Fi","Invoicing & PO billing","Backup power","Airport transfer","Tea & coffee bar"],
    scores:{c:4.8,a:4.9,com:4.9,loc:5.0,ci:4.9,v:4.8},
    aiSummary:"Corporate guests rate value highly thanks to PO billing and invoicing. The desk and meeting corner get frequent praise; gym access requires a short walk.",
    reviewsList:[["Ngozi U.","Abuja · May 2026","Corporate billing with PO numbers was seamless for our team's month-long project."],["Robert S.","Nairobi · Jul 2026","The quietest executive stay in Abuja. Wi-Fi never blinked during two weeks of calls."],["Hadiza Y.","Kano · Aug 2026","Airport pickup, check-in, everything arranged by message. Effortless."]],
    nearby:[["Transcorp Hilton","2.6 km"],["World Trade Centre","3.1 km"],["Jabi Lake Mall","6.0 km"],["Sheraton Abuja","4.4 km"]],
  },
  {
    id:"atelier-loft", name:"The Atelier Loft", area:"Eko Atlantic", city:"Lagos", img:"p6",
    price:135000, oldPrice:155000, rating:4.87, reviews:66, beds:2, baths:2, guests:4,
    type:"Designer Loft", badge:"Last-Minute Deal", badgeGold:true, instant:true, policy:"flexible",
    acreage:"Eko Atlantic", map:[0.22,0.68], featured:false, new:true, tour:false, floor:"2 Bed Loft",
    desc:"A double-height loft in the city of the future. Raw concrete softened with oak and brass, and Eko Atlantic's skyline glowing past floor-to-ceiling glass.",
    amens:["Double-height glass","Designer kitchen","City skyline view","Gym access","Smart home","Fast Wi-Fi","Valet parking","Balcony"],
    scores:{c:4.8,a:4.9,com:4.8,loc:4.9,ci:4.9,v:4.7},
    aiSummary:"Guests call it 'architectural eye candy'. A few note morning construction noise in the district — the double glazing handles most of it.",
    reviewsList:[["Kelechi O.","Lagos · Aug 2026","Architectural eye candy, and 15% off for booking within 48 hours of check-in."],["Grace L.","Accra · Aug 2026","The loft has a gallery feel. Concierge recommended an amazing rooftop dinner nearby."],["Uche A.","Lagos · Sep 2026","Checking in took ninety seconds with the keyless code."]],
    nearby:[["Eko Atlantic Boulevard","0.4 km"],["Azure Beach","2.0 km"],["City Mall, VI","3.6 km"],["Eko Hotel","3.9 km"]],
  },
  {
    id:"heritage-house", name:"Heritage House Lagos", area:"Old Ikoyi", city:"Lagos", img:"p7",
    price:120000, oldPrice:null, rating:4.93, reviews:112, beds:3, baths:2, guests:6,
    type:"Heritage Stay", badge:"Cultural Heritage", badgeGold:false, instant:false, policy:"moderate",
    acreage:"Ikoyi", map:[0.5,0.62], featured:false, new:false, tour:true, floor:"3 Bed Courtyard House",
    desc:"A lovingly restored 1950s Ikoyi courtyard house — shutters, terrazzo and antique woods, layered with contemporary comfort and Nigerian art on every wall.",
    amens:["Courtyard garden","Curated art collection","Heritage architecture","Outdoor dining","Cook available","Library","Fast Wi-Fi","Board games"],
    scores:{c:4.9,a:4.9,com:5.0,loc:4.9,ci:4.9,v:4.9},
    aiSummary:"Guests describe it as a museum that is also home. The courtyard breakfasts, curated art and the house tour are mentioned in most reviews.",
    reviewsList:[["Yewande S.","Lagos · Mar 2026","Stayed two nights and felt like I'd been to a museum that also happens to be home."],["Olivia R.","Cape Town · Jun 2026","The courtyard breakfasts were the highlight of my Nigeria trip."],["Ibrahim G.","Kano · Aug 2026","Beautiful, storied, immaculate. The house tour was a lovely touch."]],
    nearby:[["Freedom Park","2.8 km"],["Nike Art Gallery","3.2 km"],["Cathedral Church of Christ","3.0 km"],["Terra Kulture","2.4 km"]],
  },
  {
    id:"lagoon-villa", name:"The Lagoon Villa", area:"Victoria Island", city:"Lagos", img:"hero",
    price:175000, oldPrice:null, rating:4.96, reviews:151, beds:3, baths:3.5, guests:6,
    type:"Waterfront Villa", badge:"Waterfront Escapes", badgeGold:false, instant:true, policy:"moderate",
    acreage:"Victoria Island", map:[0.44,0.5], featured:true, new:false, tour:true, floor:"3 Bed Villa",
    desc:"Glass-walled living above the lagoon. An emerald-and-gold great room that turns into a lantern at dusk, with the city shimmering across the water.",
    amens:["Lagoon frontage","Floor-to-ceiling glass","Private dock","Chef's kitchen","Home cinema","Gym","Concierge on call","Paddle boards"],
    scores:{c:4.9,a:5.0,com:4.9,loc:4.9,ci:5.0,v:4.9},
    aiSummary:"The dock at sunset is the most-photographed spot in the portfolio. Generous for families; split payments made two-month stays popular with relocators.",
    reviewsList:[["Amina Z.","Abuja · Feb 2026","We watched the sunset from the dock every evening. Pure magic."],["Tom H.","London · May 2026","The AI review summary said guests love the view — it undersold it."],["Chioma P.","Lagos · Jul 2026","Split payments made a two-month stay painless. Felt like a resident."]],
    nearby:[["Lagos Yacht Club","1.8 km"],["Landmark Beach","3.0 km"],["Nike Art Gallery","5.2 km"],["Circular Bar, VI","1.6 km"]],
  },
  {
    id:"lagoon-duplex", name:"Lekki Lagoon Duplex", area:"Lekki Phase 1", city:"Lagos", img:"p10",
    price:165000, oldPrice:null, rating:4.88, reviews:59, beds:4, baths:4.5, guests:8,
    type:"Furnished Townhouse", badge:"Family Favourite", badgeGold:false, instant:true, policy:"moderate",
    acreage:"Lekki", map:[0.31,0.78], featured:false, new:true, tour:true, floor:"4 Bed Duplex",
    desc:"A warm, wood-screened duplex with a plunge-pool courtyard — made for families and long-term comfort. Quiet street, generous living, thoughtful storage.",
    amens:["Plunge pool courtyard","4 ensuite bedrooms","Full kitchen + pantry","Playroom","Office nook","Fast Wi-Fi","Secure parking for 3","Housekeeping available"],
    scores:{c:4.8,a:4.9,com:4.9,loc:4.8,ci:4.9,v:4.9},
    aiSummary:"Families love the playroom and pantry. Excellent value for 30+ nights — monthly pricing with -25% plus housekeeping keeps long stays effortless.",
    reviewsList:[["Damilola A.","Lagos · Aug 2026","We moved in for six weeks between homes. It absorbed our whole family life beautifully."],["Kate O.","Ibadan · Sep 2026","The courtyard pool saved our summer. Kids never wanted to leave."],["Femi S.","Abuja · Sep 2026","Secure parking, backup power, calm street. Long-stay done right."]],
    nearby:[["Nike Art Gallery","1.9 km"],["Lekki Market","1.2 km"],["Landmark Beach","5.0 km"],["Casa Chianti","0.8 km"]],
  },
  {
    id:"eko-icon", name:"The Eko Icon Suite", area:"Eko Atlantic", city:"Lagos", img:"p11",
    price:95000, oldPrice:null, rating:4.85, reviews:41, beds:1, baths:1.5, guests:2,
    type:"Hotel Suite", badge:"New This Season", badgeGold:false, instant:true, policy:"flexible",
    acreage:"Eko Atlantic", map:[0.25,0.62], featured:false, new:true, tour:false, floor:"1 Bed Suite",
    desc:"A boutique one-bedroom suite with soft champagne tones and city views — the smart, elegant base for a weekend in Eko Atlantic. Hotel services, apartment privacy.",
    amens:["Ocean-facing view","Hotel services","Smart TV","Rain shower","Nespresso","Fast Wi-Fi","Daily housekeeping","24/7 reception"],
    scores:{c:4.9,a:4.8,com:4.9,loc:4.8,ci:4.9,v:4.7},
    aiSummary:"Effortless for short stays — guests praise the 24/7 reception and rain shower. It books fast on event weekends.",
    reviewsList:[["Bella E.","Lagos · Sep 2026","Perfect weekend base. The reception team is lovely and the bed is cloud-soft."],["Ahmed B.","Kano · Sep 2026","Check-in took two minutes. Great Wi-Fi, great shower, great value."],["Rita N.","Port Harcourt · Sep 2026","Eko Atlantic's best budget-luxury secret."]],
    nearby:[["Eko Atlantic Promenade","0.3 km"],["Azure Beach","2.1 km"],["Palms Mall","3.4 km"]],
  },
  {
    id:"abuja-sky", name:"Abuja Sky Residence", area:"Maitama", city:"Abuja", img:"p9",
    price:190000, oldPrice:null, rating:4.91, reviews:77, beds:3, baths:3, guests:5,
    type:"Penthouse", badge:"Corporate Ready", badgeGold:false, instant:false, policy:"strict",
    acreage:"Maitama", map:[0.79,0.26], featured:false, new:false, tour:true, floor:"3 Bed Penthouse",
    desc:"High above the green hills of Abuja — a charcoal-and-brass penthouse with sunset terraces on two sides and the skyline of the capital at your feet.",
    amens:["Twin terraces","Hill & skyline views","Master suite + dressing","Chef's kitchen","Meeting corner","Fibre Wi-Fi","Gym access","Airport transfer","Backup power"],
    scores:{c:4.9,a:4.9,com:4.9,loc:5.0,ci:4.8,v:4.8},
    aiSummary:"Terraces and privacy are the recurring love letters. A couple of guests asked for earlier check-in — late checkout is available on request.",
    reviewsList:[["Moses A.","Abuja · Jun 2026","Sunset on the west terrace, briefing in the meeting corner. This is the executive life."],["Claire D.","London · Jul 2026","The most beautiful home I've stayed in in West Africa. Immaculate."],["Yakubu M.","Kaduna · Sep 2026","Quiet, secure, elegant. The booking request was confirmed within an hour."]],
    nearby:[["Transcorp Hilton","2.2 km"],["Nairobi Street restaurants","1.5 km"],["Jabi Lake","5.8 km"],["City Gate","3.0 km"]],
  },
  {
    id:"island-retreat", name:"The Island Retreat", area:"Banana Island", city:"Lagos", img:"p12",
    price:240000, oldPrice:null, rating:4.94, reviews:63, beds:3, baths:3, guests:6,
    type:"Garden Villa", badge:"Jollof Verified", badgeGold:true, instant:false, policy:"moderate",
    acreage:"Banana Island", map:[0.34,0.5], featured:false, new:false, tour:true, floor:"3 Bed Garden Villa",
    desc:"A garden villa wrapped in palms on the most exclusive island in West Africa — daybeds by a still reflecting pool, birdsong mornings and complete, guarded calm.",
    amens:["Private garden","Reflecting pool","Daybeds & hammocks","Outdoor rain shower","Chef available","Reading room","Smart home","Estate security","Boat access"],
    scores:{c:4.9,a:5.0,com:4.9,loc:5.0,ci:4.9,v:4.9},
    aiSummary:"The garden is the soul of the house — guests describe it as 'a private botanical resort'. Chef bookings sell out, so reserve ahead.",
    reviewsList:[["Oluwaseun F.","Lagos · Apr 2026","Birdsong mornings, pool reflections, total privacy. A quiet kind of luxury."],["Marie L.","Paris · Jul 2026","The rainshower under the palms is unforgettable. Villa team was superb."],["Tunde K.","Lagos · Sep 2026","Booked the chef for a birthday lunch. Effortless, memorable, immaculate."]],
    nearby:[["Banana Island Shopping Court","0.8 km"],["Ikoyi Golf Club","4.5 km"],["Villa Cinemas","5.4 km"]],
  },
];

const COLLECTIONS = [
  { id:"waterfront", name:"Waterfront Escapes", sub:"Lagoon & ocean living", img:"p3", wide:false, tall:true },
  { id:"lagos-penthouses", name:"Lagos Penthouses", sub:"Above the skyline", img:"p1", wide:false, tall:false },
  { id:"abuja-executive", name:"Abuja Executive Suites", sub:"Power stays, perfected", img:"p9", wide:false, tall:false },
  { id:"heritage", name:"Cultural Heritage Stays", sub:"Stories in every wall", img:"p7", wide:false, tall:false },
  { id:"romantic", name:"Romantic Getaways", sub:"For two, beautifully", img:"p2", wide:true, tall:false },
  { id:"family", name:"Family & Long Stays", sub:"Room to breathe", img:"p10", wide:false, tall:false },
];
const COLLECTION_MAP = {
  waterfront:["ocean-spearl","villa-azur","lagoon-villa"],
  "lagos-penthouses":["onyx","sky-garden","atelier-loft"],
  "abuja-executive":["maitama","abuja-sky"],
  heritage:["heritage-house"],
  romantic:["ocean-spearl","sky-garden","lagoon-villa"],
  family:["lagoon-duplex","island-retreat","lagoon-villa"],
};

const NEIGHBORHOODS = [
  { id:"victoria-island", name:"Victoria Island", tag:"The beating heart of Lagos", img:"p2", avg:145000, stays:2,
    desc:"Lagos' commercial centre turned nightlife capital — boardrooms by day, some of West Africa's best restaurants and rooftops by night.",
    dining:["Bogobiri House — Afro-modern fine dining","Circular Bar — lagoon-side cocktails","Rooftop Grill at the George"],
    night:["Flytime Music Hall","Landmark Beach sundowners"],
    transport:["Chauffeurs & ride apps in 5 min","Ferry terminal to Ikoyi","Helipad nearby"],
    safety:["Well-lit main arteries","Estate security at gated residences","24/7 concierge line"],
    culture:["Nike Art Gallery · Terra Kulture"] },
  { id:"ikoyi", name:"Ikoyi", tag:"Old money, green avenues", img:"p4", avg:210000, stays:2,
    desc:"Lagos' most storied residential district — quiet tree-lined streets, boutiques, golf and the lagoon on every horizon.",
    dining:["The George — fine dining","Awolowo Road cafés","Bungalow Restaurant"],
    night:["M Restaurant rooftop","The View, Ikoyi"],
    transport:["Awolowo Road shuttle","Boat services to VI","Ride apps everywhere"],
    safety:["Very low traffic noise","Gated compounds","Street-level lighting"],
    culture:["Heritage architecture walks"] },
  { id:"lekki", name:"Lekki Phase 1", tag:"The new money neighbourhood", img:"p10", avg:165000, stays:2,
    desc:"The city's fastest-growing luxury postcode — new towers, art galleries, beach clubs and the best of Lagos' creative energy.",
    dining:["Nike Art Gallery Café","Casa Chianti — Italian","Suckling Pig by Bol"],
    night:["Beach clubs on Landmark","Live at the Jazzhole"],
    transport:["Lekki-Epe expressway","Ride apps & chauffeurs","Water taxi to VI"],
    safety:["Estate security teams","CCTV at main gates","Emergency response"],
    culture:["Nike Art Gallery · Design Week"] },
  { id:"banana", name:"Banana Island", tag:"Nigeria's most exclusive address", img:"p12", avg:330000, stays:2,
    desc:"Africa's most celebrated artificial island — a private, guarded enclave of villas where the lagoon meets absolute calm.",
    dining:["Estate clubhouse","Private chefs on call","Premium provisions delivery"],
    night:["Private villa evenings","Yacht sundowners"],
    transport:["Private bridge access","Helipad on the island","Chauffeured fleets"],
    safety:["24/7 armed estate security","Access-controlled bridge","Villa alarm systems"],
    culture:["Island yachting & regattas"] },
  { id:"eko-atlantic", name:"Eko Atlantic", tag:"The city of tomorrow", img:"p11", avg:115000, stays:2,
    desc:"Built on land reclaimed from the Atlantic — Eko Atlantic is a planned city of glass towers, promenades and ocean views, rising fast.",
    dining:["Promenade cafés","Azure Beach Club","Marina restaurants"],
    night:["Beachfront lounges","Skyline bars in new towers"],
    transport:["Linked to VI by Boulevard","Ride apps 24/7","Underground parking"],
    safety:["Brand-new infrastructure","CCTV everywhere","Rapid-response security"],
    culture:["Art & design galleries opening weekly"] },
  { id:"maitama", name:"Maitama, Abuja", tag:"The gilded north", img:"p9", avg:175000, stays:2,
    desc:"Abuja's diplomatic and executive quarter — green hills, embassies and discreet luxury minutes from the Central Business District.",
    dining:["Nairobi Street restaurants","Transcorp Hilton dining","Jabi Lake eateries"],
    night:["Diplomatic lounges","Sunset at Jabi Lake"],
    transport:["Airport 35 min","Chauffeur services","Gated estate entry"],
    safety:["Diplomatic security presence","CCTV & patrols","24/7 concierge"],
    culture:["National Gallery nearby"] },
];

const EXPERIENCES = [
  { id:"cruise", name:"Lagos Lagoon Cruise", cat:"Signature", img:"exp-boat", price:85000, dur:"3 hours",
    desc:"Sunset aboard a private yacht — champagne, canapés and the skyline drifting past on the world's most storied lagoon." },
  { id:"chef", name:"Private Chef & Jollof Masterclass", cat:"Taste", img:"exp-chef", price:55000, dur:"2–3 hours",
    desc:"A Jollof Living-approved chef cooks a tasting menu in your kitchen — or teaches you the legend of the perfect jollof." },
  { id:"spa", name:"Spa & Wellness Ritual", cat:"Restore", img:"exp-spa", price:45000, dur:"90 min",
    desc:"In-residence massages, facials and private trainers, delivered to your door by vetted therapists." },
  { id:"tour", name:"Art & Heritage City Tour", cat:"Culture", img:"exp-tour", price:35000, dur:"4 hours",
    desc:"Nike Art Gallery, Freedom Park and the creative studios of Lagos, guided by artists and local historians." },
  { id:"transfer", name:"Airport Transfer", cat:"Essential", img:"p11", price:25000, dur:"45 min",
    desc:"Vetted chauffeurs in luxury SUVs — meet-and-greet, flight tracking and a chilled bottle on board." },
  { id:"events", name:"Event Curation", cat:"Bespoke", img:"p4", price:120000, dur:"Half day",
    desc:"Birthdays, proposals, corporate retreats — our events team designs and runs the whole thing." },
  { id:"shopper", name:"Personal Shopper", cat:"Bespoke", img:"p7", price:30000, dur:"3 hours",
    desc:"Pre-stock groceries, fashion-styling runs, or gift sourcing — someone brilliant, on your side." },
  { id:"festival", name:"Festival Calendar", cat:"Culture", img:"exp-tour", price:0, dur:"Ongoing",
    desc:"Detty December, Eko Jazz, art weeks — we curate tickets and tables for the moments everyone remembers." },
];

const BLOG = [
  { slug:"top-10-stays-lagos", cat:"Guides", title:"The Top 10 Stays in Lagos Right Now", date:"Aug 2026", read:"9 min", img:"p1",
    excerpt:"From sky-high penthouses to lagoon villas — the residences defining luxury travel in Lagos this season.",
    body:["Lagos has never had more beautiful places to stay. A decade of architectural ambition, a new wave of design talent and the world's most vibrant energy have combined into a stay-city without equal.","Our editors visited, slept and hosted at every residence in the current collection, scoring comfort, design, service and location. Here is what rose to the top.","Number one this season is The Onyx Penthouse, a black-marble and brass tour de force in Lekki Phase 1. The private cinema room convinced our judges within the first hour.","Rounding out the list: The Sky Garden Terrace's sunset lounge, Heritage House's restored courtyard, and the Eko Icon Suite — the smartest budget-luxury play in the city."] },
  { slug:"jollof-100", cat:"Food", title:"The Legend of Jollof, Explained Over One Plate", date:"Jul 2026", read:"6 min", img:"exp-chef",
    excerpt:"Every Nigerian claims the perfect recipe. Our private chefs settle the argument — with party rice, of course.",
    body:["There is no dish in West Africa with a bigger reputation. Jollof rice is the dish of celebration, competition and occasionally international diplomacy.","It begins with a smoky base: onions, peppers, scotch bonnet and tomato, cooked low until the flavour lays down. The rice cooks in that sauce, never after it.","Party rice takes it further — the smoky, slightly charred version cooked over a bigger flame, served at every occasion that matters.","Our private chefs run jollof masterclasses in every residence on request, with the recipe that won them their family bragging rights."] },
  { slug:"guidetodettydecember", cat:"Culture", title:"The Insider's Guide to Detty December", date:"Jun 2026", read:"11 min", img:"p4",
    excerpt:"The world's greatest month of music, parties and homecoming — and how to live it like a local.",
    body:["When the diaspora flies home, Lagos becomes the happiest city on earth. Detty December is a full month of concerts, festivals, beach days and long dinners.","Base yourself near the action — Vi, Ikoyi or Lekki Phase 1 — and let the concierge build your calendar, because events sell out in days.","Book early. Our best residences are reserved 60 to 90 days ahead, and the villa team at Villa Azur becomes the most popular address in the city.","Use the last-minute deals channel for flexibility, and always arrange transfers in advance — the December roads demand it."] },
  { slug:"work-from-lagos", cat:"Work", title:"Working From Lagos: The Executive Playbook", date:"May 2026", read:"8 min", img:"p5",
    excerpt:"Fibre Wi-Fi, power resilience and a desk with a view — how to run a serious work week from Nigeria's capital.",
    body:["Lagos and Abuja are quietly becoming remote-work capitals. English-speaking, arts-rich, food-obsessed, and connected by subsea cables to Europe in under 60ms.","The key is choosing a residence built for work: dedicated desks, backup generation, and fibre that never blinks. Our Maitama and Eko Atlantic addresses are favourites.","Extend the workday into the evening the Lagos way — rooftop dinner, jazz, then breakfast with lagoon light.","Our Corporate Ready homes support PO billing, traveler policies and monthly invoicing for companies sending teams."] },
  { slug:"longstay-guide", cat:"Living", title:"Six Weeks in Lagoon Living: A Long-Stay Diary", date:"Apr 2026", read:"7 min", img:"p12",
    excerpt:"What it actually costs, what it actually feels like, and why monthly-staying is the best way to know a city.",
    body:["We asked a guest who stayed six weeks at The Lagoon Villa to keep a diary: costs, routines, discoveries, and the moments she'd never have found as a tourist.","Week one: the split-payment plan meant the move was painless. Weekly housekeeping kept the villa perfect. Week three: she had a standing table at two restaurants and a regular boatman.","Long-stay pricing drops 25% on monthly bookings, with a digital lease agreement that covers everything in plain language.","By week six she knew the market, the barber, the sunset spot and the tide chart."] },
  { slug:"escrow-explained", cat:"Trust", title:"How Escrow Makes Luxury Stays Safe", date:"Mar 2026", read:"5 min", img:"p2",
    excerpt:"Your money is held by Jollof Living until you check in. Here's the full flow — and why it changes everything.",
    body:["The biggest fear in travel is paying for something that isn't what you were promised. Escrow removes that anxiety completely.","When you book, your payment is captured but held by Jollof Living — the host has not received it. You check in, inspect, and confirm. Only then are funds released.","If the residence isn't as described, our Dispute Resolution Centre steps in within hours, not days.","Every booking on the platform is protected this way, with a refund timeline published before you pay."] },
];

const TESTIMONIALS = [
  ["Adaeze O.","The Onyx Penthouse · Lekki","From the airport pickup to the private chef, everything felt considered. This is how luxury travel should work — with African soul."],
  ["James K.","Villa Azur · Banana Island","I've used the big platforms in thirty countries. Nothing matches this finish, this service, or this trust in payments."],
  ["Ngozi U.","Maitama Executive · Abuja","Our company books a month of suites here. Corporate invoicing, split payments, zero friction."],
  ["Tobi F.","The Sky Garden Terrace · Ikoyi","The AI concierge planned our whole weekend — boat, chef, late check-out. Three messages, done."],
  ["Hans W.","Ocean Pearl · Victoria Island","The escrow system means you pay with confidence. Check-in confirmation released the host's funds — it just works."],
  ["Yewande S.","Heritage House · Old Ikoyi","An old Lagos house, restored perfectly. I felt the culture in a way no hotel could ever give me."],
  ["Kelechi O.","The Atelier Loft · Eko Atlantic","Booked the last-minute deal two days before arriving. Best decision of the trip."],
];

const FAQS = [
  ["What are the cancellation policies?","Three transparent tiers: Flexible (full refund up to 48h before check-in), Moderate (full refund up to 5 days, 50% after), and Strict (50% up to 14 days). Each listing shows its policy clearly before you book."],
  ["How do escrow payments work?","Your payment is held securely by Jollof Living and released to the host only after you confirm check-in. If the property isn't as described, our Dispute Resolution Centre and 24/7 team step in."],
  ["Can I split payments on long stays?","Yes. For stays of 30 nights or more you can pay in two installments — 50% at booking and 50% at check-in — easing the financial burden of long-term luxury living."],
  ["What does Jollof Verified mean?","Properties that pass an in-person or video inspection earn the Jollof Verified badge. Every host also completes full KYC identity verification, and every listing is screened by our AI moderation systems."],
  ["Do I need an extended-stay agreement?","For 30+ night stays we generate a digital lease-style agreement with clear terms — signed securely in-app, with a copy stored in your encrypted documents vault."],
  ["What payment methods do you accept?","Cards (Visa, Mastercard, Verve), bank transfer, USSD, mobile money, Paystack, Flutterwave, Stripe, Apple Pay and Google Pay — in NGN, USD, GBP or EUR with real-time exchange rates."],
  ["How is my identity verified?","Three steps: government ID upload, a selfie match, and phone/SMS verification. Verified guests unlock instant booking on more residences and build trust with hosts."],
  ["Can I host an event at a residence?","Selected listings (marked 'Event Hosting') accept intimate events — birthdays, proposals, small retreats. Always request approval at booking; strict noise policies apply after 10pm."],
  ["What is Jollof Points and how do I earn them?","Earn points per night based on your membership tier (5×–15×). Redeem for discounts, late check-outs, upgrades and experiences. Your ledger is in your account."],
  ["How do I become a host?","Start the listing wizard — you'll be guided step by step through details, pricing, policies and photos. Our team then verifies and (on request) photographs your property. You can earn from your first booking."],
  ["Is there help if something goes wrong?","24/7 support on chat, phone and WhatsApp, an in-app dispute resolution centre, and one-tap emergency assistance. Median first response is under 3 minutes."],
  ["Do you support corporate travel?","Jollof Living for Business provides centralized billing, PO numbers, travel policy enforcement, monthly invoicing and a dedicated account manager. Bookings count toward your company's travel dashboard."],
];

const NOTIFS = [
  { id:1, ico:"check", title:"Booking confirmed", body:"Your stay at The Onyx Penthouse (Sep 10–17) is confirmed. Invoice #JL-2026-0912 is ready.", time:"2h ago", unread:true },
  { id:2, ico:"heart", title:"Price drop on a wishlist home", body:"The Atelier Loft dropped to ₦135,000/night — 13% below your last view.", time:"5h ago", unread:true },
  { id:3, ico:"calendar", title:"Check-in in 3 days", body:"Digital lock code for Ocean Pearl Suite unlocks Sep 6, 3:00 PM.", time:"1d ago", unread:true },
  { id:4, ico:"spark", title:"AI price alert", body:"Book Tuesday–Thursday for an estimated 15% saving on The Lagoon Villa.", time:"1d ago", unread:false },
  { id:5, ico:"wallet", title:"Payout processed", body:"₦2,574,000 sent to your Zenith account (ref JL-PO-88731).", time:"2d ago", unread:false },
  { id:6, ico:"star", title:"New review received", body:"Adaeze O. rated your stay 5.0★ — “impeccable.”", time:"3d ago", unread:false },
  { id:7, ico:"gift", title:"Referral bonus earned", body:"Tunde K. joined with your code — ₦10,000 credit added.", time:"4d ago", unread:false },
  { id:8, ico:"moon", title:"Detty December waitlist", body:"You joined the Villa Azur waitlist for Dec 20 – Jan 5. We'll alert you instantly.", time:"5d ago", unread:false },
];

const CONVERSATIONS = [
  { id:"concierge", name:"Jollof Concierge", sub:"AI · online", mine:false, online:true,
    msgs:[ {from:"bot", text:"Welcome! I'm <b>Jollof</b> ✨ — booking, transfers, chefs, anything.", t:"09:41"},
           {from:"me", text:"Book me something nice in Lekki for next weekend", t:"09:42"},
           {from:"bot", text:"Lovely! <b>The Onyx Penthouse</b> in Lekki Phase 1 is available Sep 5–7 at ₦185,000/night — it's <b>Instant Book</b>, so I can reserve it now. Want me to add an airport transfer?", t:"09:42"} ] },
  { id:"team-onyx", name:"The Onyx Penthouse", sub:"Superhost · replies ~5 min", mine:false, online:true,
    msgs:[ {from:"bot", text:"Welcome to The Onyx! Your check-in code is 4471# — the lift is express to P22.", t:"08:05"},
           {from:"me", text:"Perfect. Could we get a crib for the little one?", t:"08:11"},
           {from:"bot", text:"Already done — arriving with the welcome basket at 2pm. See you tomorrow! ✓✓", t:"08:12", read:true} ] },
  { id:"support", name:"Jollof Support", sub:"24/7 · human team", mine:false, online:true,
    msgs:[ {from:"me", text:"Hi — can I add a night to my Ocean Pearl stay?", t:"Yesterday"},
           {from:"bot", text:"Of course! Extended Sep 17→18 at your existing rate. I've sent a modification request to the host — you'll be notified within the hour.", t:"Yesterday", read:true} ] },
];

const ADMIN_STATE = {
  users:[
    ["Adebayo Ogunlesi","adebayo@jolof...","Guest · Host","Gold","Aug 2025","Verified","ok"],
    ["Adaeze Okonkwo","adaeze@...","Guest","Gold","Mar 2026","Verified","ok"],
    ["James Kepler","jkepler@...","Guest","Silver","Jan 2026","Verified","ok"],
    ["Ngozi Ude","ngoz@...","Corporate","Platinum","Nov 2025","Verified","ok"],
    ["Tunde Bakare","tunde@...","Host","Gold","Jun 2025","Verified","ok"],
    ["Hans Weber","hans@...","Guest","Bronze","Feb 2026","Verified","ok"],
    ["Chioma P","chioma@...","Guest","Gold","Dec 2025","Pending ID","warn"],
    ["Moses Adeyemi","moses@...","Host","Silver","Apr 2026","Flagged · 2FA off","warn"],
    ["Yewande Sola","yewande@...","Guest","Gold","May 2026","Verified","ok"],
    ["Femi Scores","femi@...","Host","Bronze","Aug 2026","Under review","warn"],
    ["Zainab M","zainab@...","Guest","Platinum","Sep 2025","Verified","ok"],
    ["Idris Yusuf","idris@...","Guest","—","Sep 2026","Suspended · dispute","bad"],
  ],
  moderation:[
    ["Island Retreat Photos (v2)","island-retreat","Photo set · 24 images","AI passed · awaiting human check","warn"],
    ["New listing: Banana Breeze Villa","—","New listing · Legit Lagos","KYC complete · inspection booked","info"],
    ["Review flag: 'perfect' ×19","sky-garden","Suspicious pattern","AI flagged · human review","warn"],
    ["Villa Azur Dec pricing","villa-azur","Pricing change · +20%","Payout standard","ok"],
  ],
  fraud:[
    ["FRA-0919","Booking · Villa Azur","Card mismatch + new account","72","warn"],
    ["FRA-0921","Payment · ₦1.2M","Velocity anomaly on card","54","warn"],
    ["FRA-0920","Listing · Banana Breeze","Image reuse detected","88","bad"],
    ["FRA-0917","Guest message","Phishing link in chat","61","warn"],
    ["FRA-0915","Payout change","Bank change 24h after booking","45","info"],
  ],
  campaigns:[
    ["NAIROBI-25","Detty December Preview","Oct 1 – Dec 20","Live","₦18.4M","ok"],
    ["REFER10","Give ₦10k, Get ₦10k","Rolling","Live","₦6.1M","ok"],
    ["WELCOME5","First-stay 5%","Rolling","Live","₦2.2M","ok"],
    ["VIP-GOLD","Platinum early access","Q4","Scheduled","—","info"],
    ["MAR25","March long-stay promo","Mar 2027","Draft","—","info"],
  ],
  audit:[
    ["09:12","A. Ogunlesi (Admin)","Approved listing · mod-0812","ok"],
    ["08:47","Finance Bot","Payout batch #88731 settled","info"],
    ["Yesterday","Moderator 3","Flagged review · sky-garden","warn"],
    ["Yesterday","D. Rufai (Support)","Resolved dispute #D-4410 · partial refund","ok"],
    ["2 days ago","DM: Risk","Escalated FRA-0916 to manual review","warn"],
  ],
  cms:[
    ["Home hero slide 2","Live","Jul 30","A. Ogunlesi"],
    ["Neighbourhood guide · Ikoyi","Live","Aug 12","Content team"],
    ["Blog: Detty December insider's guide","Live","Aug 24","Content team"],
    ["Promo banner · Last-minute deals","Live","Sep 1","Growth"],
    ["Help: How escrow works","Draft","—","Support"],
  ],
};

const TIERS = [
  { key:"bronze", letter:"B", name:"Bronze", req:"Every member", mult:"5×", perks:["Earn 5× Jollof Points per stay","Wishlists & price-drop alerts","Standard concierge support","Welcome baskets on select stays"], pts:"0+" },
  { key:"silver", letter:"S", name:"Silver", req:"10,000 points", mult:"8×", perks:["Earn 8× Jollof Points","Late check-out on request","Priority support line","Monthly members-only deals"], pts:"10k+" },
  { key:"gold", letter:"G", name:"Gold", req:"50,000 points", mult:"12×", featured:true, perks:["Earn 12× Jollof Points","Complimentary upgrades","Free airport transfers","Early access to new listings"], pts:"50k+" },
  { key:"platinum", letter:"P", name:"Platinum", req:"150,000 points", mult:"15×", perks:["Earn 15× Jollof Points","Dedicated account manager","Personal shopper & errand service","VIP event invitations"], pts:"150k+" },
];

const POINTS_LEDGER = [
  ["Sep 2, 2026","Shell Lagoon Experience","−12,000","redeem"],
  ["Aug 30, 2026","Stay · Ocean Pearl Suite (12n × 12×)","+52,560","earn"],
  ["Aug 1, 2026","Stay · The Sky Garden Terrace (7n × 12×)","+31,200","earn"],
  ["Jul 12, 2026","Referral bonus · Tunde K.","+10,000","earn"],
  ["Jul 4, 2026","Stay · Heritage House (3n × 12×)","+8,640","earn"],
  ["Jun 20, 2026","Gift purchase · ₦100,000 card","+1,000","earn"],
];

const HELP_CATEGORIES = [
  { id:"booking", name:"Booking & reservations", n:4, ico:"calendar" },
  { id:"payments", name:"Payments, invoices & tax", n:3, ico:"wallet" },
  { id:"hosting", name:"Hosting on Jollof Living", n:3, ico:"building" },
  { id:"trust", name:"Trust, safety & disputes", n:4, ico:"shield" },
  { id:"account", name:"Account, ID & security", n:3, ico:"lock" },
  { id:"app", name:"Using the app", n:2, ico:"phone" },
];

const ROADMAP = [
  { ph:"live", title:"Jollof Living for Business", desc:"Corporate travel portal with centralized billing, travel policy enforcement and team dashboards.", status:"live" },
  { ph:"dev", title:"Jollof Living Experiences", desc:"A standalone marketplace for local experiences, separate from property stays.", status:"dev" },
  { ph:"dev", title:"Jollof Living Homes", desc:"Six-to-twelve-month furnished rentals for relocating professionals.", status:"dev" },
  { ph:"dev", title:"Jollof Living Invest", desc:"Fractional property investment — own a share of luxury residences and earn rental income.", status:"dev" },
  { ph:"soon", title:"AR Property Previews", desc:"Augmented-reality walk-throughs through your phone camera.", status:"soon" },
  { ph:"soon", title:"Blockchain Verification", desc:"Immutable ownership and review verification on-chain.", status:"soon" },
  { ph:"soon", title:"IoT Smart Monitoring", desc:"Real-time noise, energy and occupancy monitoring for hosts.", status:"soon" },
  { ph:"soon", title:"Jollof Living Magazine", desc:"A digital lifestyle publication showcasing African luxury living.", status:"soon" },
  { ph:"soon", title:"The Jollof Card", desc:"Co-branded debit card with cashback on bookings and partner perks.", status:"soon" },
  { ph:"dev", title:"Carbon Offset Programme", desc:"Offset your travel footprint at checkout — verified projects.", status:"dev" },
];

const AUTH_METHODS = ["Email","Phone","Google","Apple","Facebook"];
const PAY_METHODS = [
  { id:"card", name:"Credit / debit card", note:"Visa, Mastercard, Verve", ico:"wallet" },
  { id:"paystack", name:"Paystack", note:"Instant · NGN & USD", ico:"bolt" },
  { id:"flutterwave", name:"Flutterwave", note:"Cards, bank, mobile money", ico:"globe" },
  { id:"bank", name:"Bank transfer", note:"All Nigerian banks", ico:"building" },
  { id:"ussd", name:"USSD", note:"*737# style dial codes", ico:"phone" },
  { id:"mobile", name:"Mobile money", note:"MTN MoMo, OPay, PalmPay", ico:"phone" },
  { id:"applepay", name:"Apple Pay", note:"One touch on iOS", ico:"lock" },
  { id:"googlepay", name:"Google Pay", note:"One touch on Android", ico:"lock" },
];
